### ISSUE TITLE
CI Content Check reports many false positives

### ISSUE THREAD

**Issue by turbolent** [onflow/developer-portal#698]
**Describe the bug**

The recently added "Developer Portal Content Check" CI check is very helpful, as it prevents broken links.

However, currently it reports many false positives.

**To Reproduce**
1. Go to e.g. https://github.com/onflow/cadence/pull/1983/checks?check_run_id=8723911821
2. See 34 errors found (169 invalid links)

**Expected behavior**

No warnings should be reported, all links are valid currently.

All links in the Cadence repo documentation are currently valid, there shouldn't be any warnings/errros. 
Just going from the top:
- in `docs/design-patterns.mdx`: `/cadence/language/capability-based-access-control` is valid, it's just absolute
- in `docs/language/access-control.md`: `contracts` is valid, it's just relative (`contracts.mdx` exists)
- in `docs/language/accounts.mdx`: `transactions` is valid, it's just relative (`transactions.md` exists)
- ...

**Comment by 10thfloor** [comment]
@turbolent 

> docs/design-patterns.mdx: /cadence/language/capability-based-access-control is valid, it's just absolute
This link is broken in GitHub.

> in docs/language/access-control.md: contracts is valid, it's just relative (contracts.mdx exists)
This link is broken in GitHub

> in docs/language/accounts.mdx: transactions is valid, it's just relative (transactions.md exists)
This link is broken in GitHub

We've changed how the site works so that you shouldn't have to think about the docs site URL scheme at all. 
You can simply follow the rule-of-thumb: "If it works (links to content properly) in GitHub, it will work on the docs site."

The only exception being links to content in the same repo, but outside oif the docs folder, in which case you must use fully-qualified URLs eg https://github.com/repo/yourdoc.md

I feel this might be the case for most of the warnings in the `check_run` you linked. 
Contributors will see a lot of warnings at first while the link checker enforces the "normalized" link requirements for the new docs site.


If you fix these links in GitHub and they still don't work on the docs site, let me know the first instance of this case, as this is a bug we need to fix!

**Comment by 10thfloor** [comment]
@turbolent 
That being said, there is still a false-negative scenario when relative links to sibling documents, in a subfolder are reported as invalid, when they work on the docs site and GitHub.

**Comment by bthaile** [comment]
Restating that some links in Cadence github don't work. here is an example of two. 
![2022-11-03 15 14 08](https://user-images.githubusercontent.com/3970376/199825557-0e208d66-ccb2-44ed-ba55-f0c78f2d2297.gif)

**Comment by turbolent** [comment]
@bthaile The links were written in a way so they would work on the developer portal, they weren't indeded to work on GitHub.

I guess we have to use relative links everywhere and cannot use absolute links?

**Comment by 10thfloor** [comment]
Correct.

**Comment by nialexsan** [comment]
static builds https://github.com/onflow/docs
