### ISSUE TITLE
external link processed as internal link

### ISSUE THREAD

**Issue by bthaile** [onflow/developer-portal#729]
**Issue**
External link has ".md" removed causing the link to be broken.

example
[interaction template page](https://developers.flow.com/tools/fcl-js/reference/interaction-templates)

"https://github.com/onflow/flips/blob/main/flips/20220503-interaction-templates.md" is an external link

Need to figure out why ".md" is removed.

Another link that chopped of the ".md"
https://developers.flow.com/tools/fcl-js/reference/proving-authentication#proving-ownership-of-a-flow-account
Link
https://github.com/onflow/fcl-js/tree/master/packages/fcl/src/wallet-provider-spec/provable-authn

**Comment by joshuahannan** [comment]
Is this related to all the link errors I am getting here? https://github.com/onflow/flow/pull/1168/checks?check_run_id=9304439733

Almost all of these links were there before and were working, so I'm not sure why they are broken in this PR

**Comment by 10thfloor** [comment]
@bthaile  This is fixed here: 
https://github.com/onflow/developer-portal/pull/717/commits/f08b5a53905effad5526ead467e31108fd65f7dd

**Comment by 10thfloor** [comment]
@joshuahannan @bthaile 

The way content is routed has changed. It's now internally consistent vs the previous site, and the check runs are how we were going to enforce the the team made the necessary updates across all connected repos.

Most of the links in the check run are indeed broken now, which is why the check run is enabled. Many documents will need to be updated. I was making the updates myself, and planned to be the one supporting the transition. Fixing the links myself and writing documentation.

Let me try to give you context here. 

Before leaving, I was in the process of updating the node operation docs. Node operation docs are complete but the check runs for those docs will still show some false-positives:  (the fix for those across _all docs_ is in progress here: https://github.com/onflow/developer-portal/pull/717)

All of the content in the `onflow/flow` repo needs to be updated because many cross-links need to be updated. 

@joshuahannan the rule for updating the links you find in the check-runs is simple: if it works in GitHub, it will work on the docs site _as long as those links are within the same folder_. 

There is still an unsolved problem with links: You can't cross link to content in separate folders in the `onflow/flow` repo  without using the fully qualified _docs site URL_ eg `https://developers.flow.com/folder/page` so that will need to be addressed as well. 
 
I'm sorry things got left in this way. I was working through things as fast as I could. Unfortunately, I wasn't able to convince technical "leadership" to commit resources to supporting these efforts, so here we are. 

There are probably a few more things the team will need to understand about the portal, and I wish I could have had more time to off-board this project _because it is not finished_; I wasn't able to find a way to make this understood amid the cost-cutting panic.

**Comment by bthaile** [comment]
PR https://github.com/onflow/developer-portal/pull/737
